### ISSUE TITLE
Wrong filename

### ISSUE THREAD

**Issue by tuttokekko** [RupertAvery/PSXPackager#12]
I have a this 7z files:
A2 Racer - Europa Tour (Netherlands).7z
Action Bass (Europe).7z
Actua Soccer 2 (Europe) (En,Fr).7z
Actua Soccer 2 (Italy).7z
Inside these files are bin and cue with the same names.

The result file with default file format or with format %FILENAME% are different from the original file names:
A2 Racer III - Europa Tour.PBP
Action Bass [PAL-Unk].PBP
Actua Soccer 2 [PAL-Unk].PBP
Actua Soccer 2 (Italy) - MERGED.PBP

**Comment by tuttokekko** [comment]
The name is get from gameInfo.db but if I ask to use FILENAME must be FILENAME (also without MERGED)

**Comment by fl4shb1c** [comment]
Same issue here so I wrote a little batch script to compensate. Create a batch file (.bat) and put it in the same folder as PSXPackager.exe with the following code:

```
@echo off
cd /D "%~dp0"

SET vari=%1
SET varo=%~dp0%output
SET varf=%~n1

if not exist %varo% mkdir %varo%

PSXPackager.exe -i %vari% -o %varo% -f "%varf%"

ren "%varo%\%varf%.PBP" "%varf%.PBP"

pause
exit
```
You can now drag any compatible source file on to this batch file and it will create an output folder in the same directory as PSXPackager.exe and convert the file to PBP.

The filename parameter is not working correctly in PSXPackager, so I've forced the filename through batch. Further to this, PSXPackager.exe forces uppercase for some reason to the filename, hence a rename command at the end to switch it back to the original.

That's my workaround for now... thanks to dev though for making a handy tool!

**Comment by RupertAvery** [comment]
Hi, if your're interested, there is a beta version of PSXPackagerGUI

https://github.com/RupertAvery/PSXPackager/releases/tag/v1.5.0

The command line tool has also been updated.

It should fix some of the filename issues.
