### ISSUE TITLE
Convert multiple .BIN files to a multi-disc .PBP

### ISSUE THREAD

**Issue by Korreia** [RupertAvery/PSXPackager#13]
I'm getting the following error when I try to combine multiple .bin into a single .pbp
![Untitled](https://user-images.githubusercontent.com/41958510/137531310-eee6073c-de58-415f-9724-169d4adad6b2.png)

Here is my .m3u file (I've added the .txt extention in order to upload here)

[Advanced Dungeons & Dragons - Iron & Blood - Warriors of Ravenloft.m3u.txt](https://github.com/RupertAvery/PSXPackager/files/7355149/Advanced.Dungeons.Dragons.-.Iron.Blood.-.Warriors.of.Ravenloft.m3u.txt)

this is the commandline I've ran: psxpackager -i "Advanced Dungeons & Dragons - Iron & Blood - Warriors of Ravenloft.m3u"

I've tried with multiple oter game and same error: Volume is not ISO-9660

any pointers for this would be great.

**Comment by RupertAvery** [comment]
Hi, if your're interested, there is a beta version of PSXPackagerGUI

https://github.com/RupertAvery/PSXPackager/releases/tag/v1.5.0
