### ISSUE TITLE
m3u -> pbp : resulting file is empty

### ISSUE THREAD

**Issue by squalou** [RupertAvery/PSXPackager#16]
Hi,0

first attempt at using your tool, with Abe Exoddus.

m3u file is fine, bin, cue, etc... I mean : I triple checked the usual suspect things.

Here's the output I get from the tool :  (note that it displays 1.4.1 even if Idownloaded 1.5.1)
 
```

PSXPackager.exe -i "Oddworld - Abe's Exoddus.m3u"
PSXPackager v1.4.1 by RupertAvery

Input : Oddworld - Abe's Exoddus.m3u
Output:
Compression Level: 5

Processing started: 18:57:46
Processing Oddworld - Abe's Exoddus.m3u
Found 2 entries

Processing completed: 00h 00m 00s

```

pretty fast huh 

Result is a directory containing a 0 octets file.

What could I do wrong ?

**Comment by RupertAvery** [comment]
What are the contents of the m3u?

**Comment by squalou** [comment]
```
Oddworld - Abe's Exoddus (Disc 1).cue
Oddworld - Abe's Exoddus (Disc 2).cue
```
did not try with absolute path, the files do exist in current directory

**Comment by takano32** [comment]
This bug may be by the input and output path containing apostrophy, I think.

But I can't re-generate bug in v1.6.1 and I would close this issue.

Thanks for your report!
