### ISSUE TITLE
the conversion does not work

### ISSUE THREAD

**Issue by JaegerFox** [RupertAvery/PSXPackager#20]
it just ends the conversion without even creating the file.
`Processing completed: 00h 00m 01s`
I'm using Windows 8.1 with the latest net framework 4.8

**Comment by master801** [comment]
This is due to the `GeneratedResourceFolders` field being always true, even if not specified in command line arguments.

https://github.com/RupertAvery/PSXPackager/blob/master/Popstation/Processing.cs#L578

v1.4.1 will not have this issue, but v1.5.0 beta and newer will have this issue.

**Comment by RupertAvery** [comment]
See the latest release

https://github.com/RupertAvery/PSXPackager/releases/tag/v1.6.0

**Comment by JaegerFox** [comment]
using the GUI works correctly, but when I want to use the CLI I get this error:
```
PSXPackager v1.6.0 by RupertAvery

Input : Silent Hill (USA).cue
Output: test.pbp
Compression level: 9

Processing started: 15:56:18
Processing Silent Hill (USA).cue

The value cannot be null (input parameter).

Processing finished: 00m 00s
```

**Comment by RupertAvery** [comment]
thanks for pointing it out.

I've updated the binary with the working code. Please re-download from the same release

Sorry, I really need to be better with testing.

**Comment by JaegerFox** [comment]
now it is working, thank you
