### ISSUE TITLE
"Must install .Net Core" or wont run on Windows 10, but its obsolete

### ISSUE THREAD

**Issue by JIVS** [RupertAvery/PSXPackager#24]
Getting this:

![image](https://user-images.githubusercontent.com/876052/216156500-ebc5d8d6-6846-432f-addc-2f99109c42cb.png)

Keep in mind if I click "yes" nothing happens.

I google .net core and I get a warning on .NET Core 3.1:
![image](https://user-images.githubusercontent.com/876052/216156767-f41509e9-dcb1-4fe6-8e5d-fe2571b01b72.png)

So I download .NET 7.0 instead.............and I keep getting the same error.

Is this a problem on my end? or this program only runs with Core 3.1?

Thanks

**Comment by luizoti** [comment]
Same problem here with 6 and 7.

**Comment by poisenbery** [comment]
I installed .NET Core 3.1 and the program ran with no issues

https://dotnet.microsoft.com/en-us/download/dotnet/3.1

**Comment by RupertAvery** [comment]
I will be adding NET 6.0 builds
