### ISSUE TITLE
This project still active?

### ISSUE THREAD

**Issue by BadBrent** [RupertAvery/PSXPackager#3]
Several of us have been looking for a batch PSX bin/cue to PBP application now for quite some time and we recently found this project.  I'm wondering if it's still being worked on or not, so if it is please let me know.  Thank you

**Comment by RupertAvery** [comment]
Yes, it is still being worked on

**Comment by BadBrent** [comment]
Wonderful...I've ran into a few issues personally since I'd love to convert my entire collection from bin/cue over to PBP format for use in RetroArch, and some of it has to do with multi-disc games not being converted properly.  I understand that if you were to put them on a PSP or something they'd have no art and I'm fine with that as this collection is meant just for direct RetroArch support for mobile devices.  I'll get more into it once I start doing more testing.
