### ISSUE TITLE
Restoring pure ZIP support

### ISSUE THREAD

**Issue by takano32** [RupertAvery/PSXPackager#38]
Pure ZIP(`*.zip`) Support may be dropped by this commit. https://github.com/RupertAvery/PSXPackager/commit/ca18d5d7583c404632c9acc6f3f0db655c90f38f

* https://github.com/RupertAvery/PSXPackager/commit/ca18d5d7583c404632c9acc6f3f0db655c90f38f#diff-72a0d633b88d24339c4a9bde59471f398fb093933854c8172901bf709b934627
* https://github.com/RupertAvery/PSXPackager/commit/ca18d5d7583c404632c9acc6f3f0db655c90f38f#diff-e88afaafeafa4678776f48d256eac77a6aa6b63be87f894a97d2a4414405fbf2

see also. [GUI Batch Page](https://github.com/RupertAvery/PSXPackager/blob/764ac5ee03aae02677eaa50bcf30fb5c43dbd7ec/PSXPackagerGUI/Pages/BatchController.cs)

**Comment by takano32** [comment]
I'll do it myself as soon as possible when my hands are free.

**Comment by RupertAvery** [comment]
Would you like to be a maintainer on this repo? You're doing a lot more contributions than me right now, and I really appreciate your work.

**Comment by takano32** [comment]
I am glad to hear from someone I respect and admire.
Please take a few moments to think about it. > maintainer
I’m not so familiar these file types yet.

That said, apart from that story, let me ask you to review and merge #36 . 😉 
Sorry for big diffs…

Maybe I should become a maintainer as well, so that I can use multiple PRs and divide them into small differences.
