### ISSUE TITLE
Multi Disc PBP decompression with more then 2 discs

### ISSUE THREAD

**Issue by bezza191** [RupertAvery/PSXPackager#4]
Hi again

Tried the new multi disc compression out using .m3u files. Seems to work great for 2 disc games, but something isnt going correctly in the decompression stage when the game contains more then 2 discs.

When compressing I noticed it mentions writing "special data" after the last disc, but on decompression it only does the first 2 discs and then says its complete. Have included a copy of the verbose output from compression and decompression below so you can see what I mean, using Legend of Dragoon as an example

> PS E:\PSX Packager testing\PSXPackager.v1.2> ./PSXPackager --verbose --input "Legend of Dragoon.m3u"
> 
> PSXPackager v1.2 by RupertAvery
> 
> Converting single file
> Input : Legend of Dragoon.m3u
> Output:
> Compression Level: 5
> 
> Found "Legend of Dragoon, The"
> Writing Disc 1
> Writing: 100%
> Writing Disc 2
> Writing: 100%
> Writing Disc 3
> Writing: 100%
> Writing Disc 4
> Writing: 100%
> Writing special data...
> 
> Conversion completed!
> PS E:\PSX Packager testing\PSXPackager.v1.2> ./PSXPackager -v -i "Legend of Dragoon, The.PBP"
> PSXPackager v1.2 by RupertAvery
> 
> Converting single file
> Input : Legend of Dragoon, The.PBP
> Output:
> Compression Level: 5
> 
> Extracting: 100%
> Conversion completed!

**Comment by RupertAvery** [comment]
Thanks for catching that!  A silly error on my part. Unfortunately I only tested with a 2-disc game.

Here's an update:

https://github.com/RupertAvery/PSXPackager/releases/tag/v1.3
