### ISSUE TITLE
Resource files cannot be found on case-sensitive filesystems.

### ISSUE THREAD

**Issue by joshbarrass** [RupertAvery/PSXPackager#48]
When running the latest release on a case-sensitive filesystem, as is typical on Linux, PSXPackager fails to find the default resources files. This is due to PSXPackager searching for `Resources/PIC0.png`, but the actual file included with the release is `Resources/PIC0.PNG`. This prevents the file from being found.

A temporary fix is to rename the resource files as any errors occur to match the cases expected by PSXPackager. However, it would be better to handle the cases correctly in the program itself.

**Steps:**
  * Download and extract v1.6.1 `psxpackager-linux-x64.zip` to a case-sensitive filesystem, e.g. ext4
  * `./psxpackager -i game.cue -o . -f "%MAINTITLE% [%MAINGAMEID%] (%REGION%)"`

**Expected results:**

PSXPackager runs without error.

**Actual results:**
```
Could not find file '/home/user/psxpackager-linux-x64/Resources/PIC0.png'.
```

**Comment by RupertAvery** [comment]
Thank you for reporting this. I have a solution that involves searching for matching files based on the filename, more or less making the resource file case-insensitive.  This works in both Windows and Linux and probably OSX too. This means that if there are more than one of the same filename but with different case, an error will be thrown. I think it unlikely that users will do this.

**Comment by RupertAvery** [comment]
Please try this build and let me know if it fixes the issue

[linux-x64.zip](https://github.com/RupertAvery/PSXPackager/files/12045336/linux-x64.zip)

**Comment by RupertAvery** [comment]
Let me know if this is still an issue in v1.6.2

**Comment by joshbarrass** [comment]
Apologies, your last reply seems to have slipped through my notifications. I just tried the latest v1.6.2 build on GitHub and am still seeing the same problem.

```
$ ./psxpackager -i game.cue -o . -f "%MAINTITLE% [%MAINGAMEID%] (%REGION%)"
PSXPackager v1.6.2 by RupertAvery

Input : game.cue
Output: .
Compression Level: 5

Processing started: 14:44:01
Processing game.cue
Using Title 'Game Title'

Could not find file '/home/user/psxpackager-linux-x64/Resources/PIC0.png'.
Processing completed: 00h 00m 00s

$ echo $?
253
```

**Comment by joshbarrass** [comment]
I just tried the build you posted above and this appears to fix the problem! :)

**Comment by takano32** [comment]
Thanks for your report!

And now, I close this ticket.
