### ISSUE TITLE
Batch PBP conversion broke during Action Bass 

### ISSUE THREAD

**Issue by BadBrent** [RupertAvery/PSXPackager#5]
I just tried your script on a large folder of games, and it broke right within the first few games, but the games that did convert to PBP were successfully tested in Retroarch so they are definitely being converted.  I should also mention I've used another utility to make a successful PBP out of this bin/cue so I know the game was ripped properly.  Here is the output from the command line:

Processing 15 of 1277:  U:\PSX Uncompressed\Action Bass (USA).cue
Could not find gameId !
Object reference not set to an instance of an object.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PSXPackager.Processing.ConvertIso(String srcIso, String srcToc, String outpath, Int32 compressionLevel, Boolean checkIfFileExists, CancellationToken cancellationToken)
   at PSXPackager.Processing.ProcessFile(String file, String outPath, String tempPath, String discs, Int32 compressionLevel, Boolean checkIfFileExists, CancellationToken cancellationToken)
   at PSXPackager.Program.ProcessFiles(IReadOnlyList1 files, String outputPath, String tempPath, String discs, Boolean checkIfFileExists, Int32 compressionLevel)
   at PSXPackager.Program.<>c__DisplayClass2_0.<Main>b__0(Options o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult1 result, Action`1 action)
   at PSXPackager.Program.Main(String[] args)
14 files processed

U:\PSXPackager.v1.3.1>

**Comment by RupertAvery** [comment]
Thanks for testing!

It appears that the gameid was not found in the gameinfo.db file. That information is actually used to generate the output filename and the internal game title which is used by PSPs.

It may be because I am using an outdated list, also I am not handling the case where a game was not found.

I'll probably default to a dummy GameID and use the filename as the game name.

**Comment by RupertAvery** [comment]
The game was in the database after all. It turns out that the filename in SYSTEM.CNF was using lowercase characters so my matching algorithm didn't find it (I expected all caps).  Anyway, I've updated it and it should be more robust now. What other games had problems?

**Comment by BadBrent** [comment]
I will run the command on my full list of 1200+ games to see which PBP conversions stop because of discid errors...my only thing is that I wish that I was given the option to add a flag where it will bypass trying to convert to PBP a game that errored out and continue on down the line.  This would enable me to create a complete NTSC list of games that fault like this during PBP conversion using your utility.

**Comment by RupertAvery** [comment]
It's good to know that a lot of people have interest in this.  Before you go and try to run it on a huge list, I will release an update that fixes the issue with Action Bass (and probably others), add some logging and continue conversion on errors. I'll probably have it out it a few hours.

**Comment by RupertAvery** [comment]
A new release has been published:

https://github.com/RupertAvery/PSXPackager/releases/tag/v1.4

It contains fixes for the Action Bass problem, and now continues to the next file if there was a problem.  Also look at the option to generate a log with -g.
