### ISSUE TITLE
GUI exe doesn't launch

### ISSUE THREAD

**Issue by orbitinstasis** [RupertAvery/PSXPackager#51]
Hi,

I've installed .net 6 and 7 SDKs and desktop runtimes, however when i try to launch the GUI exe, nothing happens. I can't find the process in task manager and have tried running the program in compatibility mode. 

I'm on windows 10.

**Comment by RupertAvery** [comment]
1.6.1 is a bit buggy. I've removed the binaries for that version.  Please try 1.6.2 (newly uploaded)

**Comment by orbitinstasis** [comment]
Spot on, that worked. I hoped I could convert pbd's to CHD but alas, no
luck. But thanks for the fix!

**Comment by takano32** [comment]
Thank you.

`GUI exe doesn't launch` is resolved and close this issue.
