### ISSUE TITLE
Access denied when input files are read-only

### ISSUE THREAD

**Issue by joshbarrass** [RupertAvery/PSXPackager#52]
Running v1.6.2 on Linux, I discovered that PSXPackager fails with an "access denied" error if it lacks _write_ permission on the input files. I could understand the problem if it lacked write permissions on the output directory, but it should be able to function without write permissions on the inputs.

**Steps:**
 1) `chmod -w game.cue game.bin`
 2) `./psxpackager -i game.cue -o . -f "%MAINTITLE% [%MAINGAMEID%] (%REGION%)"`

**Expected Output:**
PSXPackager runs without error.

**Actual Results:**
```
$ ./psxpackager -i game.cue -o . -f "%MAINTITLE% [%MAINGAMEID%] (%REGION%)"
PSXPackager v1.6.2 by RupertAvery

Input : game.cue
Output: .
Compression Level: 5

Processing started: 15:03:21
Processing game.cue

Access to the path 'game.bin' is denied.
Processing completed: 00h 00m 00s
```

This access denied error is fixed by executing `chmod +w game.cue game.bin`.

**Comment by RupertAvery** [comment]
Thanks for this.

I've found the bug, it's related to opening a file without specifying the mode.
