### ISSUE TITLE
[Bug] Version number not correct in 1.6.3

### ISSUE THREAD

**Issue by GeAd23** [RupertAvery/PSXPackager#58]
Windows 10
The version numer should read out the meta data of the executable. This number is the old one (1.6.2) but it is the release 1.6.3.
Please fix.

**Comment by takano32** [comment]
@GeAd23 Thanks for your report!

Note: https://github.com/RupertAvery/PSXPackager/blob/v1.6.3/psxpackager.props

master branch: https://github.com/RupertAvery/PSXPackager/blob/master/psxpackager.props
